### ISSUE TITLE
"Invalid base58 string" error during wallet creation

### ISSUE THREAD

**Issue by andrasfuchs** [AequitasCoinProject/AequitasFullNode#2]
I get an "Invalid base58 string" exception while trying to create a new wallet. 
I would expect to get a confirmation that the wallet was created with any problems.

To reproduce the problem:
1. Go to http://node.aequitascoin.com:38221/swagger/index.html
2. Go to the /api/Wallet/create API
3. Click "Try it out"
4. Enter the following JSON segment into the Request body field:
{
  "mnemonic": "retire tooth online neglect cluster february tackle once pet avocado this absorb",
  "password": "Wanted02",
  "passphrase": "Wanted02",
  "network": "StratisTest",
  "folderPath": "/home/node01/.stratisnode/stratis/StratisTest",
  "name": "WantedReviewerWallet02"
}
5. Click on "Execute"
6. The return code is 500 and the message is "Error: Internal Server Error"
7. If I keep open PuTTY (or any other SSH client) the node daemon displays the following exception:
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLGJ0QUN1KD0", Request id "0HLGJ0QUN1KD0:00000006": An unhandled exception was thrown by the application.
**System.FormatException: Invalid base58 string**
   at NBitcoin.Network.Parse[T](String str, Network expectedNetwork) in C:\Work\TopTal-Aequitas\AequitasFullNode\src\NBitcoin\Network.cs:line 472
   at NBitcoin.Key.Parse(String wif, String password, Network network) in C:\Work\TopTal-Aequitas\AequitasFullNode\src\NBitcoin\Key.cs:line 22
   at Stratis.Bitcoin.Features.Wallet.HdOperations.DecryptSeed(String encryptedSeed, String password, Network network) in C:\Work\TopTal-Aequitas\AequitasFullNode\src\Stratis.Bitcoin.Features.Wallet\HdOperations.cs:line 206

**Comment by andrasfuchs** [comment]
The problem was that NBitcoin's Network class changed the capitalization of one of its properties, Base58Prefixes. 

Now the /api/Wallet/create API return a code of 200 and the message is the mirror of the mnemonic,
"retire tooth online neglect cluster february tackle once pet avocado this absorb" in my case.
